# 公共配置
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static,classpath:/templates
    cache:
      period: 0


comment:
  avatar: /images/avatar.png

#server:
#  servlet:
#    context-path: /blog